octagon_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'wheel_0_joint'
  right_wheel: 'wheel_1_joint'
  publish_rate: 60.0 # defaults to 50
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 0.01]
  twist_covariance_diagonal: [0.03, 0.03, 1000000.0, 1000000.0, 1000000.0, 0.05]

  velocity_rolling_window_size: 5

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  # wheel_separation : 0.505
  # wheel_radius : 0.123
  # wheel_separation : 0.498475
  # wheel_radius : 0.13188
  
  wheel_separation : 0.508
  wheel_radius : 0.060
  
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  enable_odom_tf: true
  
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  #linear:
  #  x:
  #    has_velocity_limits    : true
  #    max_velocity           : 1.0  # m/s
  #    min_velocity           : -0.5 # m/s
  #    has_acceleration_limits: true
  #    max_acceleration       : 0.8  # m/s^2
  #    min_acceleration       : -0.4 # m/s^2
  #angular:
  #  z:
  #    has_velocity_limits    : true
  #    max_velocity           : 1.7  # rad/s
  #    has_acceleration_limits: true
  #    max_acceleration       : 1.5  # rad/s^2
